{
  "providers": {
    "Vi": [
      "Andhra Pradesh",
      "Assam",
      "Bihar Jharkhand",
      "Chennai",
      "Delhi NCR",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu Kashmir",
      "Karnataka",
      "Kerala",
      "Kolkata",
      "Madhya Pradesh Chhattisgarh",
      "Maharashtra",
      "Mumbai",
      "North East",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Tamil Nadu",
      "Telangana",
      "UP East",
      "UP West",
      "Uttarakhand",
      "West Bengal"
    ],
    "MTNL": [
      "Delhi NCR",
      "Mumbai"
    ],
    "Jio": [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar Jharkhand",
      "Chandigarh",
      "Chennai",
      "Dadra and Nagar Haveli",
      "Delhi NCR",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu Kashmir",
      "Karnataka",
      "Kerala",
      "Kolkata",
      "Madhya Pradesh Chhattisgarh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Mumbai",
      "Nagaland",
      "North East",
      "Odisha",
      "Pondicherry",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "UP East",
      "UP West",
      "Uttarakhand",
      "West Bengal"
    ],
    "BSNL": [
      "Andhra Pradesh",
      "Assam",
      "Bihar Jharkhand",
      "Chennai",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu Kashmir",
      "Karnataka",
      "Kerala",
      "Kolkata",
      "Madhya Pradesh Chhattisgarh",
      "Maharashtra",
      "North East",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Tamil Nadu",
      "UP East",
      "UP West",
      "West Bengal"
    ],
    "Airtel": [
      "Andhra Pradesh",
      "Assam",
      "Bihar Jharkhand",
      "Chennai",
      "Delhi NCR",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu Kashmir",
      "Karnataka",
      "Kerala",
      "Kolkata",
      "Madhya Pradesh Chhattisgarh",
      "Maharashtra",
      "Mumbai",
      "North East",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Tamil Nadu",
      "Telangana",
      "UP East",
      "UP West",
      "Uttarakhand",
      "West Bengal"
    ]
  }
}